### ISSUE TITLE
async_forward_entry_setup is deprecated in HA 2025.6 breaking Calendarific

### ISSUE THREAD

**Issue by kernelpanic85** [pinkywafer/Calendarific#50]
After upgrading to 2025.6, Calendarific no longer functions due to the following:

https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/calendarific/__init__.py", line 58, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

Any chance of someone updating this?
